package napakalaki;

public class JD_nombresJugadores extends javax.swing.JDialog {

    private String[] nombres;
    /**
     * Creates new form JD_nombresJugadores
     */
    public JD_nombresJugadores(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                System.exit(0);
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cuatroJugadores = new javax.swing.JCheckBox();
        jL_jugador0 = new javax.swing.JLabel();
        jL_jugador1 = new javax.swing.JLabel();
        jL_jugador2 = new javax.swing.JLabel();
        jL_jugador3 = new javax.swing.JLabel();
        jT_nombreJugador0 = new javax.swing.JTextField();
        jT_nombreJugador1 = new javax.swing.JTextField();
        jT_nombreJugador2 = new javax.swing.JTextField();
        jT_nombreJugador3 = new javax.swing.JTextField();
        cancelar = new javax.swing.JButton();
        comenzar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cuatroJugadores.setText("Cuatro jugadores");
        cuatroJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuatroJugadoresActionPerformed(evt);
            }
        });

        jL_jugador0.setText("Jugador 1");

        jL_jugador1.setText("Jugador 2");

        jL_jugador2.setText("Jugador 3");

        jL_jugador3.setText("Jugador 4");

        jT_nombreJugador0.setText("...");
        jT_nombreJugador0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_nombreJugador0ActionPerformed(evt);
            }
        });

        jT_nombreJugador1.setText("...");
        jT_nombreJugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_nombreJugador1ActionPerformed(evt);
            }
        });

        jT_nombreJugador2.setText("...");
        jT_nombreJugador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_nombreJugador2ActionPerformed(evt);
            }
        });

        jT_nombreJugador3.setText("...");
        jT_nombreJugador3.setEnabled(false);

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        comenzar.setText("Comenzar");
        comenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comenzarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(cuatroJugadores))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cancelar)
                                .addGap(51, 51, 51)
                                .addComponent(comenzar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jL_jugador0)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jT_nombreJugador0, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jL_jugador3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jT_nombreJugador3))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jL_jugador2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jT_nombreJugador2))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jL_jugador1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jT_nombreJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(cuatroJugadores)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_jugador0)
                    .addComponent(jT_nombreJugador0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_jugador1)
                    .addComponent(jT_nombreJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_jugador2)
                    .addComponent(jT_nombreJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jL_jugador3)
                    .addComponent(jT_nombreJugador3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelar)
                    .addComponent(comenzar))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cuatroJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuatroJugadoresActionPerformed
        jL_jugador3.setEnabled(cuatroJugadores.isSelected()); //los indices empiezan desde cero
        jT_nombreJugador3.setEnabled(cuatroJugadores.isSelected());

    }//GEN-LAST:event_cuatroJugadoresActionPerformed

    private void comenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comenzarActionPerformed
        if (cuatroJugadores.isSelected()) {
            nombres = new String[4];
            nombres[3] = jT_nombreJugador3.getText();
        } else
            nombres = new String[3];
        
        nombres[0] = jT_nombreJugador0.getText();
        nombres[1] = jT_nombreJugador1.getText();
        nombres[2] = jT_nombreJugador2.getText();
        this.dispose();

    }//GEN-LAST:event_comenzarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cancelarActionPerformed

    private void jT_nombreJugador0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_nombreJugador0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_nombreJugador0ActionPerformed

    private void jT_nombreJugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_nombreJugador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_nombreJugador1ActionPerformed

    private void jT_nombreJugador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_nombreJugador2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_nombreJugador2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public String[] getNombres(){
        this.setVisible(true);
        return nombres;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar;
    private javax.swing.JButton comenzar;
    private javax.swing.JCheckBox cuatroJugadores;
    private javax.swing.JLabel jL_jugador0;
    private javax.swing.JLabel jL_jugador1;
    private javax.swing.JLabel jL_jugador2;
    private javax.swing.JLabel jL_jugador3;
    private javax.swing.JTextField jT_nombreJugador0;
    private javax.swing.JTextField jT_nombreJugador1;
    private javax.swing.JTextField jT_nombreJugador2;
    private javax.swing.JTextField jT_nombreJugador3;
    // End of variables declaration//GEN-END:variables
}
